# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BUILD_SOURCE_DIRS "/prj/gsp/urm/spp_dcj_v2/tools/bpp-seq;/prj/gsp/urm/spp_dcj_v2/tools/bpp-seq")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBSOURCE_PACKAGE_FILE_NAME "libbpp-seq_2.4.1.orig")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/homes/ddoerr/mambaforge/envs/sppdcj/share/cmake-3.29/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "bpp-seq built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "STGZ;TGZ;TZ")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/prj/gsp/urm/spp_dcj_v2/tools/bpp-seq;bpp-seq;ALL;/")
set(CPACK_INSTALL_PREFIX "/prj/gsp/urm/spp_dcj_v2/tools")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "libbpp-seq 2.4.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "libbpp-seq 2.4.1")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/prj/gsp/urm/spp_dcj_v2/tools/bpp-seq/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/homes/ddoerr/mambaforge/envs/sppdcj/share/cmake-3.29/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "The Bio++ Sequence library")
set(CPACK_PACKAGE_FILE_NAME "libbpp-seq-2.4.1-Linux")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "libbpp-seq 2.4.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "libbpp-seq 2.4.1")
set(CPACK_PACKAGE_NAME "libbpp-seq")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Bio++ Development Team")
set(CPACK_PACKAGE_VERSION "2.4.1")
set(CPACK_PACKAGE_VERSION_MAJOR "2")
set(CPACK_PACKAGE_VERSION_MINOR "4")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_AUTHORS "/prj/gsp/urm/spp_dcj_v2/tools/bpp-seq/AUTHORS.txt")
set(CPACK_RESOURCE_FILE_INSTALL "/prj/gsp/urm/spp_dcj_v2/tools/bpp-seq/INSTALL.txt")
set(CPACK_RESOURCE_FILE_LICENSE "/prj/gsp/urm/spp_dcj_v2/tools/bpp-seq/COPYING.txt")
set(CPACK_RESOURCE_FILE_README "/homes/ddoerr/mambaforge/envs/sppdcj/share/cmake-3.29/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/homes/ddoerr/mambaforge/envs/sppdcj/share/cmake-3.29/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES "/build/;/html/;/BppSeq.tag/;/\\.git/;/\\.gitignore")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/prj/gsp/urm/spp_dcj_v2/tools/bpp-seq/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "bpp-seq-2.4.1")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/prj/gsp/urm/spp_dcj_v2/tools/bpp-seq/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
